Refactor/specifig usage of region
DVPE-cloud/wadtfy-custom-components pull request #32
Opened 2023-05-30 13:55 UTC by crimbler2

This PR:
- removes the region parameter from xtenant
- references the region from the wadtfy-env in xsecretstore
- references the kubernetesproviderconf from the wadfy-env in xsecretstore
- requires the region parameter in xtenantfilesystem and references it instead of reading it from the tenant env

2023-06-13 08:15 UTC, mithie requested changes
Please update the CHANGELOG.md, Chart versions and helm-docs for all changed sub charts! Since this will be a breaking change, please use a new major version for each sub chart.

2023-06-13 08:36 UTC, mithie commented on charts/v1beta1/irsa/templates/irsa-system-composition.yaml
> +          fromFieldPath: "awsRegion"
Das kommt aus der globalen EnvironmentConfig, die es einmal pro Umgebung gibt. Wird mit Crossplane installiert.

2023-06-13 12:30 UTC, crimbler2 commented
> Please update the CHANGELOG.md, Chart versions and helm-docs for all changed sub charts! Since this will be a breaking change, please use a new major version for each sub chart.

Since the charts are still on a 0.x.x version, breaking changes are acceptable. I think it's more appropriate to use a minor version.

2023-06-14 05:11 UTC, mithie approved these changes

2023-06-14 05:11 UTC, merged